/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

self.skipWaiting();
clientsClaim();

// Precache app shell resources generated by Vite build
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

const AUDIO_CACHE = 'livemate-audio-v1';
const ASSETS_CACHE = 'livemate-assets-v1';
const MANIFEST_VERSION_KEY = '/_internal/manifest-version';

// Runtime caching for audio files: CacheFirst strategy
// SW intercepts /api/audio/* requests → serve from cache if available
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/audio/'),
  new CacheFirst({
    cacheName: AUDIO_CACHE,
    matchOptions: { ignoreSearch: true },
  }),
);

// Cache FFmpeg WASM and core binaries (heavy assets)
registerRoute(
  ({ url }) => url.pathname.startsWith('/@ffmpeg/'),
  new CacheFirst({
    cacheName: ASSETS_CACHE,
  }),
);

// Listen for messages from the main app to trigger manifest-based cache sync
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SYNC_AUDIO') {
    event.waitUntil(syncAudioCache());
  }
});

async function syncAudioCache() {
  try {
    // Determine API base URL (different ports in dev vs same-origin in prod)
    const apiBase =
      self.location.port === '18180'
        ? `${self.location.protocol}//${self.location.hostname}:18181/api`
        : '/api';

    const res = await fetch(`${apiBase}/manifest`);
    if (!res.ok) return;

    const manifest = await res.json();

    const cache = await caches.open(AUDIO_CACHE);

    // Check if manifest version changed
    const storedVersionRes = await cache.match(MANIFEST_VERSION_KEY);
    const storedVersion = storedVersionRes
      ? await storedVersionRes.text()
      : null;

    if (storedVersion === manifest.version) return;

    // Cache new/changed audio files
    const expectedUrls = new Set<string>();
    for (const variant of manifest.variants) {
      const url = new URL(variant.url, self.location.origin).href;
      expectedUrls.add(url);

      const existing = await cache.match(url);
      if (!existing) {
        try {
          const audioRes = await fetch(url);
          if (audioRes.ok) {
            await cache.put(url, audioRes);
          }
        } catch {
          // Skip failed downloads, will retry next sync
        }
      }
    }

    // Remove cached files no longer in manifest
    const keys = await cache.keys();
    for (const request of keys) {
      if (
        request.url !==
          new URL(MANIFEST_VERSION_KEY, self.location.origin).href &&
        !expectedUrls.has(request.url)
      ) {
        await cache.delete(request);
      }
    }

    // Store new manifest version
    await cache.put(MANIFEST_VERSION_KEY, new Response(manifest.version));
  } catch {
    // Ignore sync errors - will retry next time
  }
}
