name: Deploy

on:
  push:
    tags:
      - 'v*' # Only triggered when there is a new Tag starting with v (created by nx release)
  workflow_dispatch: # Allow running manually from Github interface

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/setup

      - name: Deploy API first
        run: pnpm nx deploy api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: After API is live, Deploy Web safely
        run: pnpm nx deploy web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
